apiVersion: apps/v1
kind: Deployment
metadata:
  name: maha-tawazun-dep
  namespace: maha-tawazun
  labels:
    app: tawazun
    name: MahaAlotaibi 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tawazun
  template:
    metadata:
      labels:
        app: tawazun
    spec:
      containers:
        - image: 2160003120/tawazun-sda-hackathon
          name: tawazun
          env:
            - name: GOLDEN_DB_URL
              value: "mysql"
            - name: GOLDEN_DB_PORT
              value: '3306'  
            - name: GOLDEN_DB_NAME
              value: "tawazun"  
            - name: GOLDEN_DB_USERNAME
              value: "root"  
            - name: DB_PASSWORD
              value: "1234" 
          ports:
          - containerPort: 8080
