apiVersion: apps/v1
kind: Deployment
metadata:
  name: maha-mysql-dep
  namespace: maha-tawazun
  labels:
    app: tawazun
    name: MahaAlotaibi 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:latest
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "1234"
            - name: MYSQL_DATABASE
              value: "tawazun"  
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: maha-mysql-pv
              mountPath: /var/lib/mysql
      volumes:
        - name: maha-mysql-pv
          persistentVolumeClaim:
            claimName: maha-mysql-pv