apiVersion: v1
kind: PersistentVolume
metadata:
  name: maha-mysql-pv
  namespace: maha-tawazun
  labels:
    app: tawazun
    name: MahaAlotaibi 
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data" 