apiVersion: apps/v1
kind: Deployment
metadata:
  name: maha-tawazun-dep
  namespace: maha-tawazun
  labels:
    app: tawazun
    name: MahaAlotaibi 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tawazun
  template:
    metadata:
      labels:
        app: tawazun
    spec:
      containers:
        - image: 
          name: tawazun
          env:
            - name: GOLDEN_DB_URL
              value: mysql
            - name: GOLDEN_DB_PORT
              value: '3306'  
            - name: GOLDEN_DB_NAME
              value: goldenwaste  
            - name: GOLDEN_DB_USERNAME
              value: root  
            - name: GOLDEN_DB_PASSWORD
              value: DevOps2022 
          ports:
          - containerPort: 8080
