apiVersion: v1
kind: Service
metadata:
  name: maha-tawazun-svc
  namespace: maha-tawazun
  labels:
    app: tawazun
    name: MahaAlotaibi 
spec:
 selector:
   app: goldenwaste-dep-web
 type: NodePort
 ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30454
